services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra-post
    restart: always
    environment:
      CASSANDRA_USER: cassandra
      CASSANDRA_PASSWORD: cassandra
      CASSANDRA_BROADCAST_ADDRESS: 127.0.0.1
      CASSANDRA_BROADCAST_RPC_ADDRESS: 127.0.0.1
    ports:
      - 9042:9042
    volumes:
      - ./data:/var/lib/cassandra