# Generated by Django 5.1.6 on 2025-03-03 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table='tbl_comment',
        ),
        migrations.AlterModelTable(
            name='creator',
            table='tbl_creator',
        ),
        migrations.AlterModelTable(
            name='mark',
            table='tbl_mark',
        ),
        migrations.AlterModelTable(
            name='news',
            table='tbl_news',
        ),
    ]
