# Generated by Django 5.1.6 on 2025-03-03 13:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0002_alter_comment_table_alter_creator_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='marks',
            field=models.ManyToManyField(null=True, to='publisher.mark'),
        ),
        migrations.AlterField(
            model_name='creator',
            name='login',
            field=models.CharField(max_length=64, unique=True, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='mark',
            name='name',
            field=models.CharField(max_length=32, unique=True, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=64, unique=True, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
