# Generated by Django 5.1.6 on 2025-03-03 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0003_news_marks_alter_creator_login_alter_mark_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='marks',
        ),
    ]
