# Generated by Django 5.2 on 2025-05-06 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0004_remove_news_marks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
