version: '3.8'

#services:
#  postgres-rv:
#    image: postgres:16.2
#    environment:
#      POSTGRES_DB: distcomp
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#    ports:
#      - "5433:5432"
#    networks:
#      - app-network
#
#  first-service:
#    build:
#      context: .
#      dockerfile: first-service/Dockerfile
#    ports:
#      - "24110:24110"
#    environment:
#      SPRING_APPLICATION_NAME: first-service
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-rv/distcomp
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: postgres
#      SPRING_JPA_HIBERNATE_DDL_AUTO: update
#      SPRING_JPA_SHOW_SQL: true
#      SPRING_JPA_OPEN_IN_VIEW: false
#      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
#      SPRING_KAFKA_PRODUCER_KEY_SERIALIZER: org.apache.kafka.common.serialization.StringSerializer
#      SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER: org.apache.kafka.common.serialization.StringSerializer
#      SPRING_KAFKA_CONSUMER_KEY_DESERIALIZER: org.apache.kafka.common.serialization.StringDeserializer
#      SPRING_KAFKA_CONSUMER_VALUE_DESERIALIZER: org.apache.kafka.common.serialization.StringDeserializer
#    networks:
#      - app-network
#    depends_on:
#      - postgres-rv
#      - kafka
networks:
  app-network: