# Generated by Django 5.2 on 2025-05-06 18:42

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
            ],
            options={
                'db_table': 'tbl_comment',
                'managed': False,
            },
        ),
    ]
