server:
  port: 24130

spring:
  cassandra:
    port: 9042
    keyspace-name: topic_keyspace
    schema-action: CREATE_IF_NOT_EXISTS
    local-datacenter: datacenter1
    contact-points: localhost:9042
    url: jdbc:cassandra://localhost:9042/?localdatacenter=datacenter1
    username: cassandra
    password: cassandra
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

app:
  clients:
    comment:
      url: localhost:24130
    topic:
      url: localhost:24110