version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379" # Открываем порт 6379 для подключения к Redis
    volumes:
      - redis_data:/data # Постоянное хранилище данных Redis
    restart: always
    command: redis-server --appendonly yes # Включение режима AOF для сохранения данных

volumes:
  redis_data: # Объем для хранения данных Redis